### ISSUE TITLE
WP 5.5: full width blocks not stretched edge to edge in editor

### ISSUE THREAD

**Issue by dreamwhisper** [studiopress/atomic-blocks#395]
**Describe the bug**
WordPress 5.5 adjusted padding to add 10px on `.editor-styles-wrapper` as part of https://github.com/WordPress/gutenberg/pull/22213

There, full width blocks were adjusted to add right/left -10px margin to compensate. However, the CSS used is this:

```css
.block-editor-block-list__layout.is-root-container > .wp-block[data-align="full"] {
	margin-left: -10px;
	margin-right: -10px;
}
```

Atomic Blocks has an outer wrapper on blocks like Container and Advanced Columns so `> .wp-block[data-align="full"]` won't apply. As such, the blocks are no longer "full" width.

**To Reproduce**
1. Using 5.5, add a Container and Advanced Columns block.
2. Set it to full width.
3. Note that the block does not stretch edge to edge.

**Expected behavior**
Full width blocks with stretch edge to edge in the block editor.

**Screenshots**
<img width="1250" alt="Screen Shot 2020-08-12 at 9 40 17 AM" src="https://user-images.githubusercontent.com/1271053/90022120-24d3b400-dc80-11ea-9a0a-24b99e515823.png">

**Additional context**
